// src/react/CatImage.tsx
'use client'

import React, { useState, useEffect } from 'react'
import { fetchCatImage, isBrowser } from '../shared'

// Simple props interface
interface CatImageProps {
  width?: number | string
  height?: number | string
  className?: string
  style?: React.CSSProperties
}

export const CatImage: React.FC<CatImageProps> = ({ width = 300, height = 300, className, style }) => {
  // State management
  const [imageUrl, setImageUrl] = useState<string>('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<boolean>(false)

  // Main function to fetch cat image
  const loadCatImage = async () => {
    setLoading(true)
    setError(false)

    try {
      const result = await fetchCatImage()

      if (result.error || !result.data) {
        setError(true)
      } else {
        setImageUrl(result.data.url)
      }
    } catch (err) {
      setError(true)
    } finally {
      setLoading(false)
    }
  }

  // Initialize on mount (SSR-safe)
  useEffect(() => {
    if (isBrowser()) {
      loadCatImage()
    }
  }, [])

  // Computed styles
  const containerStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: width,
    height: height,
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #e1e5e9',
    backgroundColor: '#f8f9fa',
    ...style,
  }

  const imageStyle: React.CSSProperties = {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  }

  const placeholderStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    color: '#6c757d',
    fontSize: '14px',
    textAlign: 'center',
    padding: '16px',
  }

  const errorStyle: React.CSSProperties = {
    ...placeholderStyle,
    color: '#dc3545',
  }

  return (
    <div className={className} style={containerStyle}>
      {loading ? <div style={placeholderStyle}>Loading cat...</div> : error ? <div style={errorStyle}>Failed to load cat image</div> : <img src={imageUrl} alt="Random cat" style={imageStyle} />}
    </div>
  )
}

CatImage.displayName = 'CatImage'

// src/vue/CatImage.vue
<template>
  <div 
    :class="$style.container" 
    :style="{ width: normalizedWidth, height: normalizedHeight }"
  >
    <div v-if="loading" :class="$style.placeholder">
      Loading cat...
    </div>
    <div v-else-if="error" :class="$style.error">
      Failed to load cat image
    </div>
    <img
      v-else
      :src="imageUrl"
      alt="Random cat"
      :class="$style.image"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { fetchCatImage, normalizeDimension, isBrowser } from '../shared';

// Simple props interface
interface Props {
  width?: number | string;
  height?: number | string;
}

// Props with defaults
const props = withDefaults(defineProps<Props>(), {
  width: 300,
  height: 300
});

// Reactive state
const imageUrl = ref<string>('');
const loading = ref(true);
const error = ref<boolean>(false);

// Computed properties for normalized dimensions
const normalizedWidth = computed(() => normalizeDimension(props.width));
const normalizedHeight = computed(() => normalizeDimension(props.height));

// Main function to fetch cat image
const loadCatImage = async () => {
  loading.value = true;
  error.value = false;
  
  try {
    const result = await fetchCatImage();
    
    if (result.error || !result.data) {
      error.value = true;
    } else {
      imageUrl.value = result.data.url;
    }
  } catch (err) {
    error.value = true;
  } finally {
    loading.value = false;
  }
};

// Initialize on mount (SSR-safe)
onMounted(() => {
  if (isBrowser()) {
    loadCatImage();
  }
});
</script>

<style module>
.container {
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid #e1e5e9;
  background-color: #f8f9fa;
}

.image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.placeholder,
.error {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: #6c757d;
  font-size: 14px;
  text-align: center;
  padding: 16px;
}

.error {
  color: #dc3545;
}
</style>
